language: ruby
rvm:
  - 2.2.3
  - 2.3
gemfile:
  - gemfiles/sinatra_1.gemfile
  - gemfiles/sinatra_2.gemfile
env:
  - NO_COVERAGE=true
before_script:
  - bundle exec rake db:create
  - bundle exec rake db:migrate
  - bundle exec rake db:seed
